package io.algopilot.agent.position;

public enum ExitReason {
  EMERGENCY_STOP,
  RECONCILIATION_BLOCK,
  HARD_STOP_LOSS,
  RISK_LIMIT,
  STRATEGY_INVALIDATION,
  TAKE_PROFIT,
  TRAILING_STOP,
  MAX_HOLDING_TIME,
  MAX_ADVERSE_EXCURSION,
  VOLATILITY_EXIT,
  AI_DECISION_CLOSE,
  AI_DECISION_REDUCE,
  MANUAL_EXIT,
  NONE
}
