package io.algopilot.reconciliation.model;

public enum MismatchType {
  LOCAL_ORDER_MISSING_BROKER_ORDER,
  BROKER_ORDER_MISSING_LOCAL_ORDER,
  ORDER_QUANTITY_MISMATCH,
  ORDER_STATUS_MISMATCH,
  ORDER_PRICE_MISMATCH,
  FILL_MISSING_LOCALLY,
  FILL_MISSING_BROKER,
  FILL_QUANTITY_MISMATCH,
  FILL_PRICE_MISMATCH,
  FILL_FEE_MISMATCH,
  POSITION_QUANTITY_MISMATCH,
  POSITION_SIDE_MISMATCH,
  POSITION_PRICE_MISMATCH,
  BALANCE_QUANTITY_MISMATCH,
  PROVIDER_UNAVAILABLE
}
